apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: openvpn-main
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Mi
  storageClassName: longhorn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: openvpn
  labels:
    app: openvpn

spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
        - name: openvpn
          image: kylemanna/openvpn:latest
          ports:
            - name: openvpn
              containerPort: 1194
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: openvpn-main
              mountPath: "/etc/openvpn"
      volumes:
        - name: openvpn-main
          persistentVolumeClaim:
            claimName: openvpn-main
