#!/bin/bash

# General
export USER=REPLACE_ME
export INT_IF=ens10
export EXT_IF=eth0
export DEFAULT_DOMAIN=REPLACE_ME # example.com
export CLUSTER_NAME=lionkube
export CLUSTER_DOMAIN=${CLUSTER_NAME}.${DEFAULT_DOMAIN}
export ADMIN_MAIL=REPLACE_ME

# Hetzner
export HETZNER_API_TOKEN=REPLACE_ME
export HETZNER_NETWORK_NAME=kubernetes
export HETZNER_FLOATING_IP=REPLACE_ME

# Traefik
export TRAEFIK_API_DOMAIN=traefik-${CLUSTER_DOMAIN}
export TRAEFIK_API_USER=REPLACE_ME
export TRAEFIK_API_PASSWORD=REPLACE_ME

# Longhorn
export LONGHORN_DOMAIN=longhorn-${CLUSTER_DOMAIN}
export LONGHORN_USER=REPLACE_ME
export LONGHORN_PASSWORD=REPLACE_ME

# Weave Scope
export WEAVE_SCOPE_DOMAIN=scope-${CLUSTER_DOMAIN}
export WEAVE_SCOPE_USER=REPLACE_ME
export WEAVE_SCOPE_PASSWORD=REPLACE_ME
