apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  name: grafana-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
