kind: Service
apiVersion: v1
metadata:
  namespace: grafana
  name: grafana
spec:
  selector:
    app: grafana
    component: grafana
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      component: grafana
  template:
    metadata:
      labels:
        app: grafana
        component: grafana
    spec:
      initContainers:
        - name: chown-grafana-folders
          image: busybox:latest
          command: ['sh', '-c', 'chown -R 472:472 /grafana']
          volumeMounts:
            - name: config
              mountPath: /grafana

      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: GF_SERVER_ROOT_URL
              value: "https://${HOME_DASHBOARD_GRAFANA_DOMAIN}"
            - name: GF_SERVER_ENABLE_GZIP
              value: "true"
            - name: GF_SECURITY_DISABLE_GRAVATAR
              value: "true"
            - name: GF_SMTP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: grafana-admin
            - secretRef:
                name: grafana-smtp-relay
            - configMapRef:
                name: grafana-smtp-from
          volumeMounts:
            - name: config
              mountPath: /var/lib/grafana
          ports:
            - name: http
              containerPort: 3000

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: grafana-config
