apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: grafana
  name: grafana
spec:
  secretName: tls-grafana
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - ${GRAFANA_DOMAIN}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: grafana
  name: grafana
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`${GRAFANA_DOMAIN}`)
      kind: Rule
      services:
        - namespace: traefik
          name: blackhole
          port: 80
      middlewares:
        - namespace: traefik
          name: https-redirect

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: grafana
  name: grafana-secure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${GRAFANA_DOMAIN}`)
      kind: Rule
      services:
        - name: grafana
          port: 80
      middlewares:
        - namespace: traefik
          name: secure-https
  tls:
    secretName: tls-grafana
