apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: passit
  name: backup-postgresql
spec:
  # Min Hr DoM Month DoW
  schedule: '15 2 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      namespace: passit
      name: backup-postgresql
    spec:
      template:
        metadata:
          labels:
            app: passit
            component: backup-postgresql
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            mount.data.tmp: "true"
          containers:
          - name: backup-postgresql
            image: postgres:12-alpine
            imagePullPolicy: Always
            args:
              - pg_dump
              - --verbose
              - --format=c
              - --blobs
              - --host=postgresql
              - --dbname=passit
              - --username=passit
              - --no-password
              - "--file=/backup/passit.pg_dump"
            volumeMounts:
              - name: backup
                mountPath: /backup
              - name: pgpass
                mountPath: /root/.pgpass
                subPath: pgpass

          volumes:
            - name: backup
              hostPath:
                path: /data/tmp/backup/passit
                type: DirectoryOrCreate
            - name: pgpass
              secret:
                secretName: backup-postgresql-pgpass
                defaultMode: 0600
