apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: guacamole
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
