apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: guacamole
  name: backup-postgresql
spec:
  # Min Hr DoM Month DoW
  schedule: '20 2 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      namespace: guacamole
      name: backup-postgresql
    spec:
      template:
        metadata:
          labels:
            app: guacamole
            component: backup-postgresql
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            mount.data.tmp: "true"
          containers:
          - name: backup-postgresql
            image: postgres:12-alpine
            imagePullPolicy: Always
            args:
              - pg_dump
              - --verbose
              - --format=c
              - --blobs
              - --host=postgresql
              - --dbname=guacdb
              - --username=guacdb
              - --no-password
              - "--file=/backup/guacamole.pg_dump"
            volumeMounts:
              - name: backup
                mountPath: /backup
              - name: pgpass
                mountPath: /root/.pgpass
                subPath: pgpass

          volumes:
            - name: backup
              hostPath:
                path: /data/tmp/backup/guacamole
                type: DirectoryOrCreate
            - name: pgpass
              secret:
                secretName: backup-postgresql-pgpass
                defaultMode: 0600

          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                   app: guacamole
                   component: postgresql
                topologyKey: "kubernetes.io/hostname"
