apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: traefik
  name: traefik-config
data:
  config: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}

    api:
      insecure: false
      dashboard: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: traefik
  name: https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
