apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: traefik
  name: traefik-ping
spec:
  secretName: tls-traefik-ping
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - ${TRAEFIK_PING_DOMAIN}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: traefik-ping
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`${TRAEFIK_PING_DOMAIN}`)"
      kind: Rule
      services:
        - name: blackhole
          port: 80
      middlewares:
        - name: https-redirect

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: traefik-ping-secure
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`${TRAEFIK_PING_DOMAIN}`)"
      kind: Rule
      services:
        - kind: TraefikService
          name: ping@internal
  tls:
    secretName: tls-traefik-ping
