apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: imap-alerter
  name: imap-alerter-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
