apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1
          args:
            - --api.dashboard=true
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.file.filename=/traefik/config/config.yml
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.storage=acme.json
          env:
            - name: TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_EMAIL
              valueFrom:
                secretKeyRef:
                  name: traefik-config
                  key: acme_email
          volumeMounts:
            - name: config-volume
              mountPath: /traefik/config
            - name: users-dashboard
              mountPath: /traefik/users/dashboard
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
      volumes:
        - name: config-volume
          configMap:
            name: traefik-config
            items:
              - key: config
                path: config.yml
        - name: users-dashboard
          secret:
            secretName: traefik-users-dashboard
