kind: Service
apiVersion: v1
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  ports:
  - port: 80
    targetPort: 8000

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: traefik
  name: longhorn-frontend
spec:
  secretName: tls-longhorn-frontend
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - ${LONGHORN_DOMAIN}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`${LONGHORN_DOMAIN}`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
  tls:
    secretName: tls-longhorn-frontend
