kind: Service
apiVersion: v1
metadata:
  namespace: longhorn-system
  name: longhorn-frontend
  labels:
    app: longhorn-ui
spec:
  selector:
    app: longhorn-ui
  ports:
    - port: 80
      targetPort: 8000

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: longhorn-system
  name: longhorn-frontend
spec:
  secretName: tls-longhorn-frontend
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - ${LONGHORN_DOMAIN}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: longhorn-system
  name: longhorn-frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`${LONGHORN_DOMAIN}`)
      kind: Rule
      services:
        - name: blackhole
          port: 80
      middlewares:
        - namespace: traefik
          name: https-redirect

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: longhorn-system
  name: longhorn-frontend-secure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${LONGHORN_DOMAIN}`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: tls-longhorn-frontend
