apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitor-temp
  name: influxdb-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
