# Load me with "source" command of Bash
export CONFIG_COMPONENTS_LOADED=1

# Hetzner
export HETZNER_API_TOKEN=REPLACE_ME
export HETZNER_NETWORK_NAME=kubernetes
export HETZNER_FLOATING_IP=REPLACE_ME

# Traefik
export TRAEFIK_API_DOMAIN=traefik-${CLUSTER_DOMAIN}
export TRAEFIK_API_USER=REPLACE_ME
export TRAEFIK_API_PASSWORD=REPLACE_ME
export TRAEFIK_PING_DOMAIN=ping-${CLUSTER_DOMAIN}

# Longhorn
export LONGHORN_DOMAIN=longhorn-${CLUSTER_DOMAIN}
export LONGHORN_USER=REPLACE_ME
export LONGHORN_PASSWORD=REPLACE_ME
export LONGHORN_BACKUP_S3_ENDPOINT=https://REPLACE_ME
export LONGHORN_BACKUP_S3_ACCESS_KEY=REPLACE_ME
export LONGHORN_BACKUP_S3_SECRET_KEY=REPLACE_ME
