apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: nextcloud
  name: nextcloud-cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nextcloud-cron
        spec:
          restartPolicy: Never
          containers:
            - name: nextcloud-cron
              image: "busybox"
              command: [ "wget" ]
              args:
                - "-o /dev/null"
                - "https://${NEXTCLOUD_DOMAIN}/cron.php"
