apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nextcloud
  name: borgmatic-config
data:
  crontab.txt: |
    MAILTO="${ADMIN_MAIL}"
    # Min Hour DoM Month DoW Command
    30    3    *   *     *   PATH=${DOLLAR}PATH:/usr/bin /usr/bin/borgmatic --stats -v 0 2>&1

  msmtprc.sh: |
    #!/bin/sh

    cat > /etc/msmtprc << EOF
    # Set default values for all following accounts.
    defaults
    auth           on
    tls            on
    tls_starttls     on
    tls_trust_file /etc/ssl/certs/ca-certificates.crt
    logfile              /var/log/sendmail.log

    account default
    host ${DOLLAR}{MAIL_RELAY_HOST}
    port ${DOLLAR}{MAIL_PORT}
    from ${DOLLAR}{MAIL_FROM}
    user ${DOLLAR}{MAIL_USER}
    password ${DOLLAR}{MAIL_PASSWORD}

    EOF

  config.yaml: |
    location:
      source_directories:
        - /mnt/source

      repositories:
        - borg@${NEXTCLOUD_BORG_SSH_HOST}:/backup/${CLUSTER_NAME}-nextcloud

    storage:
      compression: lz4
      archive_name_format: 'backup-{now}'
      ssh_command: 'ssh -p ${NEXTCLOUD_BORG_SSH_PORT}'

    retention:
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 12
      keep_yearly: 10
      prefix: 'backup-'

    consistency:
      checks:
        - repository
        - archives
      check_last: 3
      prefix: 'backup-'

    hooks:
      before_backup:
        - echo "Starting a backup job."
      after_backup:
        - echo "Backup created."
      on_error:
        - echo "Error while creating a backup."

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nextcloud
  name: borgmatic-mail-config
data:
  MAIL_RELAY_HOST: "${MAIL_HOST}"
  MAIL_PORT: "${MAIL_PORT}"
  MAIL_FROM: "${CLUSTER_NAME}.borgmatic"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nextcloud
  name: borgmatic
  labels:
    app: borgmatic
spec:
  selector:
    matchLabels:
      app: borgmatic
  template:
    metadata:
      labels:
        app: borgmatic
    spec:
      nodeSelector:
        mount.data.nextcloud: "true"

      initContainers:
        - name: init-repo
          image: b3vis/borgmatic
          imagePullPolicy: Always
          args:
            - "borgmatic"
            - "--init"
            - "--encryption"
            - "repokey-blake2"
          env:
            - name: TZ
              value: ${TIMEZONE}
          envFrom:
            - configMapRef:
                name: borgmatic-mail-config
            - secretRef:
                name: borgmatic-mail-creds
            - secretRef:
                name: borgmatic-passphrase
          volumeMounts:
            - name: conf
              mountPath: /etc/borgmatic.d
            - name: ssh
              mountPath: /root/.ssh

      containers:
        - name: borgmatic
          image: b3vis/borgmatic
          imagePullPolicy: Always
          env:
            - name: TZ
              value: ${TIMEZONE}
          envFrom:
            - configMapRef:
                name: borgmatic-mail-config
            - secretRef:
                name: borgmatic-mail-creds
            - secretRef:
                name: borgmatic-passphrase
          volumeMounts:
            - name: nextcloud
              mountPath: /mnt/source/nextcloud
              readOnly: true
            - name: conf
              mountPath: /etc/borgmatic.d
            - name: ssh
              mountPath: /root/.ssh

      volumes:
        - name: nextcloud
          hostPath:
            path: /data/nextcloud
            type: DirectoryOrCreate
        - name: conf
          configMap:
            name: borgmatic-config
        - name: ssh
          projected:
            defaultMode: 0600
            sources:
            - secret:
                name: borgmatic-ssh-key
            - configMap:
                name: borgmatic-known-hosts
