apiVersion: v1
kind: ConfigMap
metadata:
  namespace: traefik
  name: traefik-config
data:
  config: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
      traefik:
        address: ":8080"

    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}

    api:
      # API will only be exposed through secure IngressRoute
      insecure: true
      dashboard: true
