apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik
spec:
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
    - name: websecure
      protocol: TCP
      port: 443
  selector:
    app: traefik

---

apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: blackhole
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: blackhole
