apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1
          args:
            - --configFile=/traefik/config/config.yml
          env:
            - name: TRAEFIK_CERTIFICATESRESOLVERS_DEFAULT_ACME_EMAIL
              valueFrom:
                secretKeyRef:
                  name: traefik-config
                  key: acme_email
          volumeMounts:
            - name: config
              mountPath: /traefik/config
            - name: routers
              mountPath: /traefik/routers
            - name: users
              mountPath: /traefik/users
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
      volumes:
        - name: config
          configMap:
            name: traefik-config
            items:
              - key: config
                path: config.yml
        - name: routers
          projected:
            sources:
              - configMap:
                  name: traefik-routers-dashboard
                  items:
                    - key: routers
                      path: dashboard.yml
        - name: users
          projected:
            sources:
              - secret:
                  name: traefik-users-dashboard
                  items:
                    - key: users
                      path: dashboard
