# General
USER=REPLACE_ME
INT_IF=ens10
EXT_IF=eth0

# Hetzner
HETZNER_API_TOKEN=REPLACE_ME
HETZNER_NETWORK_NAME=REPLACE_ME
HETZNER_FLOATING_IP=REPLACE_ME

# Traefik
TRAEFIK_ADMIN_MAIL=REPLACE_ME
TRAEFIK_DASHBOARD_DOMAIN=REPLACE_ME
TRAEFIK_DASHBOARD_USER=REPLACE_ME
TRAEFIK_DASHBOARD_PASSWORD=REPLACE_ME
