#cloud-config
groups:
  - docker

users:
  - name: REPLACE_ME
    groups: docker
    sudo: ALL=(ALL:ALL) ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - REPLACE_ME

packages:
  - ufw
package_update: true
package_upgrade: true

runcmd:
  - ufw allow OpenSSH
  - ufw --force enable
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers REPLACE_ME' /etc/ssh/sshd_config
  - reboot
