apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: "${HETZNER_API_TOKEN}"
  network: "${HETZNER_NETWORK_NAME}"

---

apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
  namespace: kube-system
stringData:
  token: "${HETZNER_API_TOKEN}"

---

apiVersion: v1
kind: Namespace
metadata:
  name: fip-controller
  labels:
    name: fip-controller

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fip-controller-config
  namespace: fip-controller
data:
  config.json: |
    {
      "hcloud_floating_ips": [ "${HETZNER_FLOATING_IP}" ],
      "node_address_type": "external"
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: fip-controller-secrets
  namespace: fip-controller
stringData:
  HCLOUD_API_TOKEN: ${HETZNER_API_TOKEN}
