alertmanager:
  persistentVolume:
    enabled: false
    storageClass: longhorn

pushgateway:
  persistentVolume:
    enabled: false
    storageClass: longhorn

server:
  persistentVolume:
    enabled: false
    storageClass: longhorn
  retention: "1d"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
           app: nextcloud
           component: nextcloud
        topologyKey: "kubernetes.io/hostname"

nodeExporter:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
