alertmanager:
  persistentVolume:
    enabled: false
    storageClass: longhorn

pushgateway:
  persistentVolume:
    enabled: false
    storageClass: longhorn

server:
  persistentVolume:
    enabled: false
    storageClass: longhorn
  retention: "1d"

nodeExporter:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
