{
 "title": "Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_cpu_seconds_total{}, kubernetes_node)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(max(node_filesystem_size_bytes) by (kubernetes_node,device) / 1024 / 1024 / 1024, \"_0_kubernetes_node\", \"$1\", \"kubernetes_node\", \"(.*)\")"
    },
    {
     "expr": "label_replace(max(node_filesystem_avail_bytes) by (kubernetes_node,device) / 1024 / 1024 / 1024, \"_0_kubernetes_node\", \"$1\", \"kubernetes_node\", \"(.*)\")"
    },
    {
     "expr": "label_replace((max(node_filesystem_size_bytes - node_filesystem_avail_bytes) by (kubernetes_node,device)) / 1024 / 1024 / 1024, \"_0_kubernetes_node\", \"$1\", \"kubernetes_node\", \"(.*)\")"
    }
   ]
  },
  { "title": "[[node]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node) (irate(node_cpu_seconds_total{mode=\"idle\",kubernetes_node=~\"[[node]]\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "node_load1{kubernetes_node=~\"[[node]]\"} / on(app) kube_node_status_capacity_cpu_cores{node=~\"[[node]]\"}",
     "legendFormat": "Load / core"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"[[node]]\"}-node_memory_MemAvailable_bytes{kubernetes_node=~\"[[node]]\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"[[node]]\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}